const Data = [
  {
    id: 1,
    title: "new Song",
    description: "this song is sing by the arjit singh",
    image: "pht.png",
    ThumbImage: "pht.png",
    author: "yash kelhe",
    views: 232,
    timeStamp: "2 days",
  },
  {
    id: 2,
    title: "new Song",
    description: "this song is sing by the arjit singh",
    image: "pht.png",
    ThumbImage: "pht.png",
    author: "yash kelhe",
    views: 232,
    timeStamp: "2 days",
  },
  {
    id: 3,
    title: "new Song",
    description: "this song is sing by the arjit singh",
    image: "pht.png",
    ThumbImage: "pht.png",
    author: "yash kelhe",
    views: 232,
    timeStamp: "2 days",
  },
  {
    id: 4,
    title: "new Song",
    description: "this song is sing by the arjit singh",
    image: "pht.png",
    ThumbImage: "pht.png",
    author: "yash kelhe",
    views: 232,
    timeStamp: "2 days",
  },
  {
    id: 5,
    title: "new Song",
    description: "this song is sing by the arjit singh",
    image: "pht.png",
    ThumbImage: "pht.png",
    author: "yash kelhe",
    views: 232,
    timeStamp: "2 days",
  },
];

export default Data;
